old_sound_rabbit_mq:
    connections:
        default:
            host: 'rabbit1'
            user:     'rabbitmq'
            password: 'rabbitmq'
#    producers:
#        # use 'old_sound_rabbit_mq.task_producer' service to send data.
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
    consumers:
        task:
            connection:       default
            exchange_options: { name: 'product_exchange', type: direct }
            queue_options:    { name: 'product_q'}
            callback:         App\Consumer\DefaultConsumer
