old_sound_rabbit_mq:
  connections:
    default:
      host: 'rabbit1'
      user:     'rabbitmq'
      password: 'rabbitmq'
  producers:
    #Producer used in listener
    product_updater:
      connection:       default
      exchange_options: { name: 'product_exchange', type: direct }
  consumers:
    #Receives message from product_exchange when listener is fired
    product_receiver_rpc_consumer:
      connection:       default
      exchange_options: { name: 'product_exchange', type: direct }
      queue_options:
        name: 'product_rpc_q'
        routing_keys:
          - 'product_with_rpc'
      callback: App\Consumer\ProductReceiverRpcConsumer
    #Receives message from product_exchange when listener is fired
    product_receiver_guzzle_consumer:
      connection:       default
      exchange_options: { name: 'product_exchange', type: direct }
      queue_options:
        name: 'product_guzzle_q'
        routing_keys:
          - 'product_with_guzzle'
      callback: App\Consumer\ProductReceiverGuzzleConsumer
  rpc_servers:
    #RPC server that returns product data
    product_rpc_consumer:
      exchange_options:
        name: 'product_exchange'
        type: direct
      queue_options:
        name: 'product_call_rpc_q'
        routing_keys:
          - 'product.rpc'
      callback: App\Consumer\ProductRpcConsumer
  rpc_clients:
    #RPC client included in product_receiver_consumer
    product_rpc_client:
      connection: default