old_sound_rabbit_mq:
  connections:
    default:
      host: 'rabbit1'
      user:     'rabbitmq'
      password: 'rabbitmq'
  producers:
    #Producer used in listener
    product_updater:
      connection:       default
      exchange_options: { name: 'product_exchange', type: direct }
  consumers:
    #Receives message from product_exchange when listener is fired
    product_receiver_consumer:
      connection:       default
      exchange_options: { name: 'product_exchange', type: direct }
      queue_options:
        name: 'product_q'
        routing_keys:
          - 'product'
      callback: App\Consumer\ProductReceiverConsumer
  rpc_servers:
    #RPC server that returns product data
    product_rpc_consumer:
      exchange_options:
        name: 'product_exchange'
        type: direct
      queue_options:
        name: 'product_q.rpc'
        routing_keys:
          - 'product.rpc'
      callback: App\Consumer\ProductRpcConsumer
  rpc_clients:
    #RPC client included in product_receiver_consumer
    product_rpc_client:
      connection: default